service: glue-stream-test # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "*"

resources:
  Resources:
  #   MyDatabase:
  #     Type: AWS::Glue::Database
  #     Properties:
  #       CatalogId: !Ref AWS::AccountId
  #     DatabaseInput:
  #       Name: glue-streaming-test-db
  #
  #   MyTable:
  #     Type: AWS::Glue::Table
  #     Properties:
  #       CatalogId: !Ref AWS::AccountId
  #       DatabaseName: !Ref MyDatabase
  #       TableInput:
  #         PartitionKeys:
  #           - Column
  #         Retention: Integer
  #         StorageDescriptor:
  #           StorageDescriptor
  #         TableType: String
  #         ViewExpandedText: String
  #         ViewOriginalText: String



    MyBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: glue-streaming-test

    MyJobRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Allow"
              Principal:
                Service:
                  - "glue.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Path: "/"
        Policies:
          -
            PolicyName: "root"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                -
                  Effect: "Allow"
                  Action: "*"
                  Resource: "*"

    MyJob:
      Type: AWS::Glue::Job
      Properties:
        Name: example-job
        Role: !Ref MyJobRole
        GlueVersion: "1.0"
        ExecutionProperty:
          MaxConcurrentRuns : 1
        Command:
          Name: gluestreaming
          ScriptLocation:
            Fn::Join:
              - ""
              - - s3://
                - glue-streaming-test/
                - scripts/
                - ExampleJob.scala
        DefaultArguments:
          "--job-language": scala
          "--class": com.jeremydowens.AWSGlue.GlueApp
          "--TempDir": s3://glue-streaming-test/temp/
          "--job-bookmark-option": job-bookmark-disable
