service: glue-stream-test # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "*"

resources:
  Resources:
    MyStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: sensehat-records
        RetentionPeriodHours: 24
        ShardCount: 1

    MyDatabase:
      Type: AWS::Glue::Database
      Properties:
        CatalogId: !Ref AWS::AccountId
        DatabaseInput:
          Name: glue-streaming-example-db

    MyTable:
      Type: AWS::Glue::Table
      Properties:
        CatalogId: !Ref AWS::AccountId
        DatabaseName: !Ref MyDatabase
        TableInput:
          Name: glue-streaming-example-table
          Parameters: {"classification": "json"}

          Retention: 24
          StorageDescriptor:
            Parameters: {"endpointUrl": "https://kinesis.us-east-1.amazonaws.com","streamName": "sensehat-records","typeOfData": "kinesis"}
            Columns:
              - Name: client_id
                Type: string
              - Name: temperature
                Type: double
              - Name: humidity
                Type: double
              - Name: pressure
                Type: double
              - Name: pitch
                Type: double
              - Name: roll
                Type: double
              - Name: yaw
                Type: double
              - Name: timestamp
                Type: timestamp
              - Name: count
                Type: bigint
            InputFormat: TextInputFormat
            Location: !Ref MyStream
            OutputFormat: HiveIgnoreKeyTextOutputFormat
            SerdeInfo:
              Parameters: {"paths": "client_id,count,humidity,pitch,pressure,roll,temperature,timestamp,yaw"}
              SerializationLibrary: org.openx.data.jsonserde.JsonSerDe

    MyBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: glue-streaming-test

    MyJobRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Allow"
              Principal:
                Service:
                  - "glue.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Path: "/"
        Policies:
          -
            PolicyName: "root"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                -
                  Effect: "Allow"
                  Action: "*"
                  Resource: "*"

    MyJob:
      Type: AWS::Glue::Job
      Properties:
        Name: example-job
        Role: !Ref MyJobRole
        GlueVersion: "1.0"
        ExecutionProperty:
          MaxConcurrentRuns : 1
        Command:
          Name: gluestreaming
          ScriptLocation:
            Fn::Join:
              - ""
              - - s3://
                - glue-streaming-test/
                - scripts/
                - ExampleJob.scala
        DefaultArguments:
          "--job-language": scala
          "--class": com.jeremydowens.AWSGlue.ExampleJob
          "--TempDir": s3://glue-streaming-test/temp/
          "--job-bookmark-option": job-bookmark-disable
