################################################################################
# This cloudformation template is updated when changes are made. It contains   #
# all of the required resources for Kinesis, Glue, S3, and IAM that are used   #
# in the glue streaming data example.                                          #
#                                                                              #
# author: jeremy@jeremydowens.com                                              #
################################################################################

AWSTemplateFormatVersion: 2010-09-09

# The cloudformation wizard will prompt for these parameters to be entered.
# Note that s3 bucket names are globally unique and if you enter a previously
# used name, the entire stack creation will fail.
Parameters:
  JobName:
    Description: The name of the glue job you wish to create
    Type: String
  ResourceBucketName:
    Description: The bucket where scripts and data will be stored
    Type: String
  StreamName:
    Description: The name of the kinesis stream you wish to create
    Type: String
  DatabaseName:
    Description: The name of the glue database you wish to create
    Type: String
  TableName:
    Description: The name of the glue table you wish to create
    Type: String

Resources:
  MyStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Sub '${StreamName}'
      RetentionPeriodHours: 24
      ShardCount: 1

  MyDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Sub '${DatabaseName}'

  MyTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref MyDatabase
      TableInput:
        Name: !Sub '${TableName}'
        Parameters: {"classification": "json"}

        Retention: 24
        StorageDescriptor:
          Parameters: {"endpointUrl": "https://kinesis.us-east-1.amazonaws.com", "streamName": {Ref: MyStream}, "typeOfData": "kinesis"}
          Columns:
            - Name: client_id
              Type: string
            - Name: temperature
              Type: double
            - Name: humidity
              Type: double
            - Name: pressure
              Type: double
            - Name: pitch
              Type: double
            - Name: roll
              Type: double
            - Name: yaw
              Type: double
            - Name: timestamp
              Type: timestamp
            - Name: count
              Type: bigint
          InputFormat: TextInputFormat
          Location: !Ref MyStream
          OutputFormat: HiveIgnoreKeyTextOutputFormat
          SerdeInfo:
            Parameters: {"paths": "client_id,count,humidity,pitch,pressure,roll,temperature,timestamp,yaw"}
            SerializationLibrary: org.openx.data.jsonserde.JsonSerDe

  MyBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub '${ResourceBucketName}'

  MyJobRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "glue.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "*"
                Resource: "*"

  MyJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub '${JobName}'
      Role: !Ref MyJobRole
      GlueVersion: "1.0"
      MaxCapacity: 2.0
      ExecutionProperty:
        MaxConcurrentRuns : 1
      Command:
        Name: gluestreaming
        ScriptLocation: !Sub 's3://${ResourceBucketName}/scripts/ExampleJob.scala'
      DefaultArguments:
        "--job-language": scala
        "--class": com.jeremydowens.AWSGlue.ExampleJob
        "--TempDir": !Sub 's3://${ResourceBucketName}/temp/'
        "--job-bookmark-option": job-bookmark-disable
        "--STREAM_NAME": !Sub '${StreamName}'
        "--BUCKET_NAME": !Sub '${ResourceBucketName}'
        "--DATABASE_NAME": !Sub '${DatabaseName}'
        "--TABLE_NAME": !Sub '${TableName}'
