name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up environment
      run: |
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_SECRET_ID }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY }}
        export AWS_DEFAULT_REGION=us-east-1
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Compile Job
      run: sbt clean compile
    - name: Upload to S3
      run: |
        aws s3 sync src/main/scala/ s3://aws-glue-streaming-example/scripts/
        aws s3 sync data/ s3://aws-glue-streaming-example/data/
